//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ysm.Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ysm.Downloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All.
        /// </summary>
        public static string Button_CancelAll {
            get {
                return ResourceManager.GetString("Button_CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Button_Paste {
            get {
                return ResourceManager.GetString("Button_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Button_Skip {
            get {
                return ResourceManager.GetString("Button_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download the playlist or the video?.
        /// </summary>
        public static string Question_PlaylistOrVideo {
            get {
                return ResourceManager.GetString("Question_PlaylistOrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video.
        /// </summary>
        public static string Text_Video {
            get {
                return ResourceManager.GetString("Text_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos.
        /// </summary>
        public static string Text_Videos {
            get {
                return ResourceManager.GetString("Text_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting to.
        /// </summary>
        public static string Title_ConvertingTo {
            get {
                return ResourceManager.GetString("Title_ConvertingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to:.
        /// </summary>
        public static string Title_ConvertTo {
            get {
                return ResourceManager.GetString("Title_ConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download only audio (mp3).
        /// </summary>
        public static string Title_DownloadAudio {
            get {
                return ResourceManager.GetString("Title_DownloadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Title_Downloading {
            get {
                return ResourceManager.GetString("Title_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Original.
        /// </summary>
        public static string Title_DownloadOriginal {
            get {
                return ResourceManager.GetString("Title_DownloadOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging video and audio.
        /// </summary>
        public static string Title_Merging {
            get {
                return ResourceManager.GetString("Title_Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string Title_OutputFolder {
            get {
                return ResourceManager.GetString("Title_OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid YouTube video/playlist ID or URL!.
        /// </summary>
        public static string Warning_invalid_id {
            get {
                return ResourceManager.GetString("Warning_invalid_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No links or Id in clipboard!.
        /// </summary>
        public static string Warning_no_id {
            get {
                return ResourceManager.GetString("Warning_no_id", resourceCulture);
            }
        }
    }
}
