//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ysm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ysm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A.Q..
        /// </summary>
        public static string About_FAQ {
            get {
                return ResourceManager.GetString("About_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YSM - YouTube Subscription Manager.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have the latest version of YSM..
        /// </summary>
        public static string About_Update1 {
            get {
                return ResourceManager.GetString("About_Update1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An updated version of YSM application is available..
        /// </summary>
        public static string About_Update2 {
            get {
                return ResourceManager.GetString("About_Update2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string About_UserGuide {
            get {
                return ResourceManager.GetString("About_UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string About_Website {
            get {
                return ResourceManager.GetString("About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About YSM.
        /// </summary>
        public static string Button_About {
            get {
                return ResourceManager.GetString("Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Button_AddPlaylist {
            get {
                return ResourceManager.GetString("Button_AddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Button_AddToFavorites {
            get {
                return ResourceManager.GetString("Button_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All as Unwatched.
        /// </summary>
        public static string Button_AllUnwatched {
            get {
                return ResourceManager.GetString("Button_AllUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Videos.
        /// </summary>
        public static string Button_AllVideos {
            get {
                return ResourceManager.GetString("Button_AllVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All as Watched.
        /// </summary>
        public static string Button_AllWatched {
            get {
                return ResourceManager.GetString("Button_AllWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoplay.
        /// </summary>
        public static string Button_Autoplay {
            get {
                return ResourceManager.GetString("Button_Autoplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all watch history..
        /// </summary>
        public static string Button_ClearHistory {
            get {
                return ResourceManager.GetString("Button_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Players.
        /// </summary>
        public static string Button_CloseAllPlayers {
            get {
                return ResourceManager.GetString("Button_CloseAllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Favorites.
        /// </summary>
        public static string Button_CloseFavorites {
            get {
                return ResourceManager.GetString("Button_CloseFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Player.
        /// </summary>
        public static string Button_ClosePlayer {
            get {
                return ResourceManager.GetString("Button_ClosePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Button_Colors {
            get {
                return ResourceManager.GetString("Button_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Button_Comments {
            get {
                return ResourceManager.GetString("Button_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy  Channels Url.
        /// </summary>
        public static string Button_CopyChannels {
            get {
                return ResourceManager.GetString("Button_CopyChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Channel Url.
        /// </summary>
        public static string Button_CopyChannelUrl {
            get {
                return ResourceManager.GetString("Button_CopyChannelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Text.
        /// </summary>
        public static string Button_CopyText {
            get {
                return ResourceManager.GetString("Button_CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Url.
        /// </summary>
        public static string Button_CopyUrl {
            get {
                return ResourceManager.GetString("Button_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Videos Url.
        /// </summary>
        public static string Button_CopyVideos {
            get {
                return ResourceManager.GetString("Button_CopyVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Video Url.
        /// </summary>
        public static string Button_CopyVideoUrl {
            get {
                return ResourceManager.GetString("Button_CopyVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string Button_CreateCategory {
            get {
                return ResourceManager.GetString("Button_CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Colors.
        /// </summary>
        public static string Button_CustomColors {
            get {
                return ResourceManager.GetString("Button_CustomColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Button_Cut {
            get {
                return ResourceManager.GetString("Button_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Before Yesterday.
        /// </summary>
        public static string Button_DayBeforeYesterday {
            get {
                return ResourceManager.GetString("Button_DayBeforeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Color.
        /// </summary>
        public static string Button_DefaultColor {
            get {
                return ResourceManager.GetString("Button_DefaultColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask me this again..
        /// </summary>
        public static string Button_DontAskAgain {
            get {
                return ResourceManager.GetString("Button_DontAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All.
        /// </summary>
        public static string Button_DownloadAll {
            get {
                return ResourceManager.GetString("Button_DownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All Videos.
        /// </summary>
        public static string Button_DownloadAllVideos {
            get {
                return ResourceManager.GetString("Button_DownloadAllVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Subscriptions.
        /// </summary>
        public static string Button_DownloadNewSubscriptions {
            get {
                return ResourceManager.GetString("Button_DownloadNewSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Videos.
        /// </summary>
        public static string Button_DownloadNewVideos {
            get {
                return ResourceManager.GetString("Button_DownloadNewVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Videos.
        /// </summary>
        public static string Button_DownloadVideos {
            get {
                return ResourceManager.GetString("Button_DownloadVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Button_Favorites {
            get {
                return ResourceManager.GetString("Button_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Button_Feedback {
            get {
                return ResourceManager.GetString("Button_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Button_Folders {
            get {
                return ResourceManager.GetString("Button_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Button_Help {
            get {
                return ResourceManager.GetString("Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Button_History {
            get {
                return ResourceManager.GetString("Button_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string Button_Iterations {
            get {
                return ResourceManager.GetString("Button_Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seven Days.
        /// </summary>
        public static string Button_LastSeven {
            get {
                return ResourceManager.GetString("Button_LastSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Thirty Days.
        /// </summary>
        public static string Button_LastThirty {
            get {
                return ResourceManager.GetString("Button_LastThirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string Button_Licence {
            get {
                return ResourceManager.GetString("Button_Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate.
        /// </summary>
        public static string Button_Locate {
            get {
                return ResourceManager.GetString("Button_Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Button_Logout {
            get {
                return ResourceManager.GetString("Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark....
        /// </summary>
        public static string Button_Mark {
            get {
                return ResourceManager.GetString("Button_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Button_Marker {
            get {
                return ResourceManager.GetString("Button_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers.
        /// </summary>
        public static string Button_Markers {
            get {
                return ResourceManager.GetString("Button_Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Unwatched.
        /// </summary>
        public static string Button_MarkUnwatched {
            get {
                return ResourceManager.GetString("Button_MarkUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Watched.
        /// </summary>
        public static string Button_MarkWatched {
            get {
                return ResourceManager.GetString("Button_MarkWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist.
        /// </summary>
        public static string Button_NewPlaylist {
            get {
                return ResourceManager.GetString("Button_NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Button_Open {
            get {
                return ResourceManager.GetString("Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Channel.
        /// </summary>
        public static string Button_OpenChannel {
            get {
                return ResourceManager.GetString("Button_OpenChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Channel in Browser.
        /// </summary>
        public static string Button_OpenChannelInBrowser {
            get {
                return ResourceManager.GetString("Button_OpenChannelInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Channel Page.
        /// </summary>
        public static string Button_OpenChannelPage {
            get {
                return ResourceManager.GetString("Button_OpenChannelPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Channels.
        /// </summary>
        public static string Button_OpenChannels {
            get {
                return ResourceManager.GetString("Button_OpenChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Favorites.
        /// </summary>
        public static string Button_OpenFavorites {
            get {
                return ResourceManager.GetString("Button_OpenFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In {xy}.
        /// </summary>
        public static string Button_OpenInBrowser {
            get {
                return ResourceManager.GetString("Button_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open (New Tab).
        /// </summary>
        public static string Button_OpenTab {
            get {
                return ResourceManager.GetString("Button_OpenTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Videos.
        /// </summary>
        public static string Button_OpenVideos {
            get {
                return ResourceManager.GetString("Button_OpenVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Videos Page.
        /// </summary>
        public static string Button_OpenVideosPage {
            get {
                return ResourceManager.GetString("Button_OpenVideosPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Button_Overview {
            get {
                return ResourceManager.GetString("Button_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Button_Paste {
            get {
                return ResourceManager.GetString("Button_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause watch history..
        /// </summary>
        public static string Button_PauseHistory {
            get {
                return ResourceManager.GetString("Button_PauseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Button_Player {
            get {
                return ResourceManager.GetString("Button_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Video.
        /// </summary>
        public static string Button_PlayerNext {
            get {
                return ResourceManager.GetString("Button_PlayerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Video.
        /// </summary>
        public static string Button_PlayerPrevious {
            get {
                return ResourceManager.GetString("Button_PlayerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Button_PlayerReload {
            get {
                return ResourceManager.GetString("Button_PlayerReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Button_Playlists {
            get {
                return ResourceManager.GetString("Button_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string Button_RemoveAll {
            get {
                return ResourceManager.GetString("Button_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen Closed Tab.
        /// </summary>
        public static string Button_ReopenClosedTab {
            get {
                return ResourceManager.GetString("Button_ReopenClosedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat All.
        /// </summary>
        public static string Button_RepeatAll {
            get {
                return ResourceManager.GetString("Button_RepeatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Cloud Data.
        /// </summary>
        public static string Button_ReplaceCloudData {
            get {
                return ResourceManager.GetString("Button_ReplaceCloudData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace local data.
        /// </summary>
        public static string Button_ReplaceLocalData {
            get {
                return ResourceManager.GetString("Button_ReplaceLocalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Google for.
        /// </summary>
        public static string Button_SearchGoogle {
            get {
                return ResourceManager.GetString("Button_SearchGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Button_Settings {
            get {
                return ResourceManager.GetString("Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Subscriptions.
        /// </summary>
        public static string Button_ShowAllSubscriptions {
            get {
                return ResourceManager.GetString("Button_ShowAllSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Subscriptions With Video Only.
        /// </summary>
        public static string Button_ShowSubscriptionsWithVideo {
            get {
                return ResourceManager.GetString("Button_ShowSubscriptionsWithVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Button_Shuffle {
            get {
                return ResourceManager.GetString("Button_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By Date.
        /// </summary>
        public static string Button_SortDate {
            get {
                return ResourceManager.GetString("Button_SortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By Title.
        /// </summary>
        public static string Button_SortTitle {
            get {
                return ResourceManager.GetString("Button_SortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Button_Subscriptions {
            get {
                return ResourceManager.GetString("Button_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Button_Today {
            get {
                return ResourceManager.GetString("Button_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on watch history..
        /// </summary>
        public static string Button_TurnOnHistory {
            get {
                return ResourceManager.GetString("Button_TurnOnHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string Button_Tutorial {
            get {
                return ResourceManager.GetString("Button_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Unwatched Videos.
        /// </summary>
        public static string Button_UnwatchedVideos {
            get {
                return ResourceManager.GetString("Button_UnwatchedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Videos.
        /// </summary>
        public static string Button_UpdateVideos {
            get {
                return ResourceManager.GetString("Button_UpdateVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string Button_UserGuide {
            get {
                return ResourceManager.GetString("Button_UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Button_Validate {
            get {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos &amp; Subscriptions.
        /// </summary>
        public static string Button_VideosChannels {
            get {
                return ResourceManager.GetString("Button_VideosChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Button_View {
            get {
                return ResourceManager.GetString("Button_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Later.
        /// </summary>
        public static string Button_WatchLater {
            get {
                return ResourceManager.GetString("Button_WatchLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Button_Yesterday {
            get {
                return ResourceManager.GetString("Button_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription is not visible in the current view (Show subscriptions with video only)..
        /// </summary>
        public static string Info_ChangeSubscriptionView1 {
            get {
                return ResourceManager.GetString("Info_ChangeSubscriptionView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the subscription view mode to &quot;Show all subscriptions&quot;?.
        /// </summary>
        public static string Info_ChangeSubscriptionView2 {
            get {
                return ResourceManager.GetString("Info_ChangeSubscriptionView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this channel | from the playlist?.
        /// </summary>
        public static string Question_Channel_Delete_From_Playlist {
            get {
                return ResourceManager.GetString("Question_Channel_Delete_From_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your YSM  YouTube account data? It won&apos;t impact your YouTube account.\nThis change requires restart..
        /// </summary>
        public static string Question_DeleteAccount {
            get {
                return ResourceManager.GetString("Question_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all of your favorites?.
        /// </summary>
        public static string Question_Favorites_RemoveAll {
            get {
                return ResourceManager.GetString("Question_Favorites_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import will overwrite your current category structure. Do you want to proceed?.
        /// </summary>
        public static string Question_Import {
            get {
                return ResourceManager.GetString("Question_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all videos in all categories as watched?.
        /// </summary>
        public static string Question_MarkAllVideoWatched {
            get {
                return ResourceManager.GetString("Question_MarkAllVideoWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to open _count_ pages in the _browser_?.
        /// </summary>
        public static string Question_Open {
            get {
                return ResourceManager.GetString("Question_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this playlist.
        /// </summary>
        public static string Question_Playlist_Delete {
            get {
                return ResourceManager.GetString("Question_Playlist_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all videos from your playlist?.
        /// </summary>
        public static string Question_Playlist_RemoveAll {
            get {
                return ResourceManager.GetString("Question_Playlist_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscription process has not finished yet..
        /// </summary>
        public static string Question_Unsub1 {
            get {
                return ResourceManager.GetString("Question_Unsub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application? .
        /// </summary>
        public static string Question_Unsub2 {
            get {
                return ResourceManager.GetString("Question_Unsub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unsubscribe from {xy} channels?.
        /// </summary>
        public static string Question_Unsubscirbe_m {
            get {
                return ResourceManager.GetString("Question_Unsubscirbe_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from &apos;{xy}&apos;?.
        /// </summary>
        public static string Question_Unsubscirbe_s {
            get {
                return ResourceManager.GetString("Question_Unsubscirbe_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all of your &apos;watch-later&apos; videos?.
        /// </summary>
        public static string Question_WatchLater_RemoveAll {
            get {
                return ResourceManager.GetString("Question_WatchLater_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Settings_Downloads {
            get {
                return ResourceManager.GetString("Settings_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Settings_History {
            get {
                return ResourceManager.GetString("Settings_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Settings_Notifications {
            get {
                return ResourceManager.GetString("Settings_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Settings_Player {
            get {
                return ResourceManager.GetString("Settings_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Note button..
        /// </summary>
        public static string Settings_ShowBookmarkBtn {
            get {
                return ResourceManager.GetString("Settings_ShowBookmarkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comments button..
        /// </summary>
        public static string Settings_ShowCommentsBtn {
            get {
                return ResourceManager.GetString("Settings_ShowCommentsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Download button..
        /// </summary>
        public static string Settings_ShowDownloadBtn {
            get {
                return ResourceManager.GetString("Settings_ShowDownloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Download button..
        /// </summary>
        public static string Settings_ShowDownloadIcon {
            get {
                return ResourceManager.GetString("Settings_ShowDownloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Favorites button..
        /// </summary>
        public static string Settings_ShowFavoritesBtn {
            get {
                return ResourceManager.GetString("Settings_ShowFavoritesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Favorites button..
        /// </summary>
        public static string Settings_ShowFavoritesIcon {
            get {
                return ResourceManager.GetString("Settings_ShowFavoritesIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Locate button..
        /// </summary>
        public static string Settings_ShowLocateBtn {
            get {
                return ResourceManager.GetString("Settings_ShowLocateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Locate button..
        /// </summary>
        public static string Settings_ShowLocateIcon {
            get {
                return ResourceManager.GetString("Settings_ShowLocateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &apos;New Tab&apos; button..
        /// </summary>
        public static string Settings_ShowNewtabIcon {
            get {
                return ResourceManager.GetString("Settings_ShowNewtabIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Patreon Button (if available)..
        /// </summary>
        public static string Settings_ShowPatreonBtn {
            get {
                return ResourceManager.GetString("Settings_ShowPatreonBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Playlists button..
        /// </summary>
        public static string Settings_ShowPlaylistBtn {
            get {
                return ResourceManager.GetString("Settings_ShowPlaylistBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Playlists button..
        /// </summary>
        public static string Settings_ShowPlaylistIcon {
            get {
                return ResourceManager.GetString("Settings_ShowPlaylistIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &apos;Watch Later&apos; button..
        /// </summary>
        public static string Settings_ShowWatchLaterBtn {
            get {
                return ResourceManager.GetString("Settings_ShowWatchLaterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &apos;Watch Later&apos; button..
        /// </summary>
        public static string Settings_ShowWatchlaterIcon {
            get {
                return ResourceManager.GetString("Settings_ShowWatchlaterIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start YSM on system startup..
        /// </summary>
        public static string Settings_StartApp {
            get {
                return ResourceManager.GetString("Settings_StartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start YSM in the Notification Area..
        /// </summary>
        public static string Settings_StartAppNotification {
            get {
                return ResourceManager.GetString("Settings_StartAppNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start YSM on the Taskbar..
        /// </summary>
        public static string Settings_StartAppTaskbar {
            get {
                return ResourceManager.GetString("Settings_StartAppTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Settings_Subscriptions {
            get {
                return ResourceManager.GetString("Settings_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string Settings_Sync {
            get {
                return ResourceManager.GetString("Settings_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Settings_Videos {
            get {
                return ResourceManager.GetString("Settings_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are already data in the cloud. How would you like to perform the synchronization?.
        /// </summary>
        public static string Sync_Title1 {
            get {
                return ResourceManager.GetString("Sync_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Replace Cloud Data&apos; only if you wish to overwrite your existing data in the cloud with that present locally on your machine..
        /// </summary>
        public static string Sync_Title2 {
            get {
                return ResourceManager.GetString("Sync_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ’Replace local data&apos; only if you wish to overwrite your existing local data with your cloud data..
        /// </summary>
        public static string Sync_Title3 {
            get {
                return ResourceManager.GetString("Sync_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Text_Comment {
            get {
                return ResourceManager.GetString("Text_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Text_Day {
            get {
                return ResourceManager.GetString("Text_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Text_Days {
            get {
                return ResourceManager.GetString("Text_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all videos as unwatched which are newer than.
        /// </summary>
        public static string Text_MarkAllUnwatched {
            get {
                return ResourceManager.GetString("Text_MarkAllUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all videos as watched which are older than.
        /// </summary>
        public static string Text_MarkAllWatched {
            get {
                return ResourceManager.GetString("Text_MarkAllWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xy new subscription..
        /// </summary>
        public static string Text_NewSubscription {
            get {
                return ResourceManager.GetString("Text_NewSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xy new subscriptions..
        /// </summary>
        public static string Text_NewSubscriptions {
            get {
                return ResourceManager.GetString("Text_NewSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xy new video..
        /// </summary>
        public static string Text_NewVideo {
            get {
                return ResourceManager.GetString("Text_NewVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xy new videos..
        /// </summary>
        public static string Text_NewVideos {
            get {
                return ResourceManager.GetString("Text_NewVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist URL.
        /// </summary>
        public static string Text_PlaylistUrl {
            get {
                return ResourceManager.GetString("Text_PlaylistUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist URL is invalid..
        /// </summary>
        public static string Text_PlaylistUrlInvalid {
            get {
                return ResourceManager.GetString("Text_PlaylistUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video added to the playlist (xy)..
        /// </summary>
        public static string Text_VideoAddedPlaylist {
            get {
                return ResourceManager.GetString("Text_VideoAddedPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Video is not visible in the current view(Show only unwatched videos)..
        /// </summary>
        public static string Text_VideoNotVisible1 {
            get {
                return ResourceManager.GetString("Text_VideoNotVisible1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the video display mode to &quot;Show all videos&quot;?.
        /// </summary>
        public static string Text_VideoNotVisible2 {
            get {
                return ResourceManager.GetString("Text_VideoNotVisible2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow global hotkeys..
        /// </summary>
        public static string Title_AllowGlobalHotkeys {
            get {
                return ResourceManager.GetString("Title_AllowGlobalHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask to continue playback..
        /// </summary>
        public static string Title_AskToContinuePlayback {
            get {
                return ResourceManager.GetString("Title_AskToContinuePlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask to mark all videos as watched at startup..
        /// </summary>
        public static string Title_AskToMarkAllVideosWatched {
            get {
                return ResourceManager.GetString("Title_AskToMarkAllVideosWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Space to stop/start investigation..
        /// </summary>
        public static string Title_AssistanceStop {
            get {
                return ResourceManager.GetString("Title_AssistanceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Title_Comments {
            get {
                return ResourceManager.GetString("Title_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control playlist with global hotkeys..
        /// </summary>
        public static string Title_ControlPlaylistGlobalHotkey {
            get {
                return ResourceManager.GetString("Title_ControlPlaylistGlobalHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting.
        /// </summary>
        public static string Title_Converting {
            get {
                return ResourceManager.GetString("Title_Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete: delete local account data.
        /// </summary>
        public static string Title_DeleteAccount {
            get {
                return ResourceManager.GetString("Title_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Title_Download {
            get {
                return ResourceManager.GetString("Title_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Audio:.
        /// </summary>
        public static string Title_DownloadingAudio {
            get {
                return ResourceManager.GetString("Title_DownloadingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Subscriptions.
        /// </summary>
        public static string Title_DownloadingSubscriptions {
            get {
                return ResourceManager.GetString("Title_DownloadingSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Video:.
        /// </summary>
        public static string Title_DownloadingVideo {
            get {
                return ResourceManager.GetString("Title_DownloadingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Videos.
        /// </summary>
        public static string Title_DownloadingVideos {
            get {
                return ResourceManager.GetString("Title_DownloadingVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Title_Downloding {
            get {
                return ResourceManager.GetString("Title_Downloding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Title_Favorites {
            get {
                return ResourceManager.GetString("Title_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites: .
        /// </summary>
        public static string Title_FooterFavorites {
            get {
                return ResourceManager.GetString("Title_FooterFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History:.
        /// </summary>
        public static string Title_FooterHistory {
            get {
                return ResourceManager.GetString("Title_FooterHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview:.
        /// </summary>
        public static string Title_FooterOverview {
            get {
                return ResourceManager.GetString("Title_FooterOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions:.
        /// </summary>
        public static string Title_FooterSubscriptions {
            get {
                return ResourceManager.GetString("Title_FooterSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Later:.
        /// </summary>
        public static string Title_FooterWatchLater {
            get {
                return ResourceManager.GetString("Title_FooterWatchLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Title_History {
            get {
                return ResourceManager.GetString("Title_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product key you have entered is invalid..
        /// </summary>
        public static string Title_InvalidProductKey {
            get {
                return ResourceManager.GetString("Title_InvalidProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string Title_Iterations {
            get {
                return ResourceManager.GetString("Title_Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Autoplay turned on. .
        /// </summary>
        public static string Title_KeepAutoplayTurnedOn {
            get {
                return ResourceManager.GetString("Title_KeepAutoplayTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Title_Logout {
            get {
                return ResourceManager.GetString("Title_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as &quot;unwatched&quot;.
        /// </summary>
        public static string Title_MarkAsUnwatched {
            get {
                return ResourceManager.GetString("Title_MarkAsUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as &quot;watched&quot;.
        /// </summary>
        public static string Title_MarkAsWatched {
            get {
                return ResourceManager.GetString("Title_MarkAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark videos as watched at startup..
        /// </summary>
        public static string Title_MarkVideosWatchedStartup {
            get {
                return ResourceManager.GetString("Title_MarkVideosWatchedStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes..
        /// </summary>
        public static string Title_Minutes {
            get {
                return ResourceManager.GetString("Title_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string Title_NewCategory {
            get {
                return ResourceManager.GetString("Title_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist.
        /// </summary>
        public static string Title_NewPlaylist {
            get {
                return ResourceManager.GetString("Title_NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 New Subscription.
        /// </summary>
        public static string Title_NewSubscription {
            get {
                return ResourceManager.GetString("Title_NewSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {xy} New Subscriptions.
        /// </summary>
        public static string Title_NewSubscriptions {
            get {
                return ResourceManager.GetString("Title_NewSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show new subscriptions notification window..
        /// </summary>
        public static string Title_NewSubscriptionsNW {
            get {
                return ResourceManager.GetString("Title_NewSubscriptionsNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 New Video.
        /// </summary>
        public static string Title_NewVideo {
            get {
                return ResourceManager.GetString("Title_NewVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {xy} New Videos.
        /// </summary>
        public static string Title_NewVideos {
            get {
                return ResourceManager.GetString("Title_NewVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show new videos notification window..
        /// </summary>
        public static string Title_NewVideosNW {
            get {
                return ResourceManager.GetString("Title_NewVideosNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in {xy}:.
        /// </summary>
        public static string Title_OpenInBrowser {
            get {
                return ResourceManager.GetString("Title_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist(_XY_) already contains the video: .
        /// </summary>
        public static string Title_PlaylistContainsVideo {
            get {
                return ResourceManager.GetString("Title_PlaylistContainsVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Title_Playlists {
            get {
                return ResourceManager.GetString("Title_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Or Create a New Playlist....
        /// </summary>
        public static string Title_PlaylistWindow {
            get {
                return ResourceManager.GetString("Title_PlaylistWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play notification sound..
        /// </summary>
        public static string Title_PlayNotiicationSound {
            get {
                return ResourceManager.GetString("Title_PlayNotiicationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product key:.
        /// </summary>
        public static string Title_ProductKey {
            get {
                return ResourceManager.GetString("Title_ProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Title_Search {
            get {
                return ResourceManager.GetString("Title_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial has been expired..
        /// </summary>
        public static string Title_SerialWindowTitle {
            get {
                return ResourceManager.GetString("Title_SerialWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application startup position:.
        /// </summary>
        public static string Title_SettingsApplicationStartupPosition {
            get {
                return ResourceManager.GetString("Title_SettingsApplicationStartupPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new videos every.
        /// </summary>
        public static string Title_SettingsAutoDownload {
            get {
                return ResourceManager.GetString("Title_SettingsAutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close YSM to system tray..
        /// </summary>
        public static string Title_SettingsCloseSystemTray {
            get {
                return ResourceManager.GetString("Title_SettingsCloseSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start YSM in the default position..
        /// </summary>
        public static string Title_SettingsDefaultPosition {
            get {
                return ResourceManager.GetString("Title_SettingsDefaultPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads Folder:.
        /// </summary>
        public static string Title_SettingsDownloads {
            get {
                return ResourceManager.GetString("Title_SettingsDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start playing Youtube videos..
        /// </summary>
        public static string Title_SettingsEnableAutoplay {
            get {
                return ResourceManager.GetString("Title_SettingsEnableAutoplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Title_SettingsHidden {
            get {
                return ResourceManager.GetString("Title_SettingsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start YSM in the last saved position..
        /// </summary>
        public static string Title_SettingsLastPosition {
            get {
                return ResourceManager.GetString("Title_SettingsLastPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Side.
        /// </summary>
        public static string Title_SettingsLeft {
            get {
                return ResourceManager.GetString("Title_SettingsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start YSM in full screen..
        /// </summary>
        public static string Title_SettingsMaximized {
            get {
                return ResourceManager.GetString("Title_SettingsMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize YSM to system tray..
        /// </summary>
        public static string Title_SettingsMinimizeSystemTray {
            get {
                return ResourceManager.GetString("Title_SettingsMinimizeSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Youtube Ads..
        /// </summary>
        public static string Title_SettingsRemoveAds {
            get {
                return ResourceManager.GetString("Title_SettingsRemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Side.
        /// </summary>
        public static string Title_SettingsRight {
            get {
                return ResourceManager.GetString("Title_SettingsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only the last fifteen videos..
        /// </summary>
        public static string Title_SettingsShowLast15Videos {
            get {
                return ResourceManager.GetString("Title_SettingsShowLast15Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show subscriptions only with unwatched videos..
        /// </summary>
        public static string Title_SettingsShowSubscriptionsOnlyWithUnwatchedVideos {
            get {
                return ResourceManager.GetString("Title_SettingsShowSubscriptionsOnlyWithUnwatchedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar position:.
        /// </summary>
        public static string Title_SettingsSidebarPosition {
            get {
                return ResourceManager.GetString("Title_SettingsSidebarPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all videos.
        /// </summary>
        public static string Title_ShowAllVideos {
            get {
                return ResourceManager.GetString("Title_ShowAllVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show channel tooltip..
        /// </summary>
        public static string Title_ShowChannelTooltip {
            get {
                return ResourceManager.GetString("Title_ShowChannelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show view sidebar..
        /// </summary>
        public static string Title_ShowSidebar {
            get {
                return ResourceManager.GetString("Title_ShowSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toolbar tooltips..
        /// </summary>
        public static string Title_ShowToolbarTooltip {
            get {
                return ResourceManager.GetString("Title_ShowToolbarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Title_Subscriptions {
            get {
                return ResourceManager.GetString("Title_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing YSM Data.
        /// </summary>
        public static string Title_SynchronizingData {
            get {
                return ResourceManager.GetString("Title_SynchronizingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video added to the playlist..
        /// </summary>
        public static string Title_VideoAddedPlaylist {
            get {
                return ResourceManager.GetString("Title_VideoAddedPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Title_Views {
            get {
                return ResourceManager.GetString("Title_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Later.
        /// </summary>
        public static string Title_WatchLater {
            get {
                return ResourceManager.GetString("Title_WatchLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to YSM.
        /// </summary>
        public static string Title_Welcome {
            get {
                return ResourceManager.GetString("Title_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut category or subscription (CTRL+X).
        /// </summary>
        public static string Tooltip_Cut {
            get {
                return ResourceManager.GetString("Tooltip_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new videos (F5).
        /// </summary>
        public static string Tooltip_DownloadNewVideos {
            get {
                return ResourceManager.GetString("Tooltip_DownloadNewVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Tooltip_Feedback {
            get {
                return ResourceManager.GetString("Tooltip_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all Videos as watched.
        /// </summary>
        public static string Tooltip_MarkAllWatched {
            get {
                return ResourceManager.GetString("Tooltip_MarkAllWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new category (F3).
        /// </summary>
        public static string Tooltip_NewCategory {
            get {
                return ResourceManager.GetString("Tooltip_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new playlist (F3).
        /// </summary>
        public static string Tooltip_NewPlaylist {
            get {
                return ResourceManager.GetString("Tooltip_NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open assistance.
        /// </summary>
        public static string Tooltip_OpenAssitance {
            get {
                return ResourceManager.GetString("Tooltip_OpenAssitance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open channel in the primary browser.
        /// </summary>
        public static string Tooltip_OpenChannel {
            get {
                return ResourceManager.GetString("Tooltip_OpenChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste category or subscription (CTRL+V).
        /// </summary>
        public static string Tooltip_Paste {
            get {
                return ResourceManager.GetString("Tooltip_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category or unsubscribe (del.).
        /// </summary>
        public static string Tooltip_Remove {
            get {
                return ResourceManager.GetString("Tooltip_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a playlist (.Del).
        /// </summary>
        public static string Tooltip_RemovePlaylist {
            get {
                return ResourceManager.GetString("Tooltip_RemovePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a category (F2).
        /// </summary>
        public static string Tooltip_Rename {
            get {
                return ResourceManager.GetString("Tooltip_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a playlist (F2).
        /// </summary>
        public static string Tooltip_RenamePlaylist {
            get {
                return ResourceManager.GetString("Tooltip_RenamePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string Tooltip_Settings {
            get {
                return ResourceManager.GetString("Tooltip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new subscriptions (F6).
        /// </summary>
        public static string Tooltip_UpdateSubscriptions {
            get {
                return ResourceManager.GetString("Tooltip_UpdateSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open video in the primary browser.
        /// </summary>
        public static string Tootip_OpenVideo {
            get {
                return ResourceManager.GetString("Tootip_OpenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key.
        /// </summary>
        public static string WindowTitle_ProductKey {
            get {
                return ResourceManager.GetString("WindowTitle_ProductKey", resourceCulture);
            }
        }
    }
}
